# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

# Raw binary FileDescriptorProto for hello.proto
# (175 bytes, verified with protobuf Python library)
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bhello.proto\x12\x05hello""\n\x0cHelloRequest'
    b'\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name"&\n\nHelloReply'
    b'\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2=\n\x07Greeter'
    b'\x122\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply'
    b'B\x06Z\x04./pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'Z\x04./pb'
